/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Workshop Creator Workflows",
  "tagline": "¿Listo para aprender algo nuevo?",
  "url": "https://sncrwf.github.io",
  "trailingSlash": false,
  "baseUrl": "/workshops-es/",
  "favicon": "img/favicon.ico",
  "organizationName": "sncrwf",
  "projectName": "workshops-es",
  "staticDirectories": [
    "static"
  ],
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "warn",
  "markdown": {
    "mermaid": true
  },
  "themes": [
    "@docusaurus/theme-mermaid"
  ],
  "plugins": [
    "docusaurus-plugin-sass",
    null,
    [
      "@docusaurus/plugin-content-docs",
      {
        "path": "labs/telework-vancouver-101",
        "id": "teleworkvancouver-101",
        "routeBasePath": "labs/telework-vancouver-101",
        "sidebarPath": "/Users/lucasalmeida/Documents/GitHub/workshops-es/labs/telework-vancouver-101/sidebar.js",
        "showLastUpdateAuthor": false,
        "showLastUpdateTime": false,
        "breadcrumbs": false
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "path": "labs/telework-201_vancouver",
        "id": "telework-201_vancouver",
        "routeBasePath": "labs/telework-201_vancouver",
        "sidebarPath": "/Users/lucasalmeida/Documents/GitHub/workshops-es/labs/telework-201_vancouver/sidebar.js",
        "showLastUpdateAuthor": false,
        "showLastUpdateTime": false,
        "breadcrumbs": false
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "path": "labs/collaborate-vancouver",
        "id": "collaboratevancouver",
        "routeBasePath": "labs/collaborate-vancouver",
        "sidebarPath": "/Users/lucasalmeida/Documents/GitHub/workshops-es/labs/collaborate-vancouver/sidebar.js",
        "breadcrumbs": false
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "path": "labs/spokegen",
        "id": "spokegen",
        "routeBasePath": "labs/spokegen",
        "sidebarPath": "/Users/lucasalmeida/Documents/GitHub/workshops-es/labs/spokegen/sidebar.js",
        "showLastUpdateAuthor": false,
        "showLastUpdateTime": false,
        "breadcrumbs": false
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "path": "labs/rpa",
        "id": "rpa",
        "routeBasePath": "labs/rpa",
        "sidebarPath": "/Users/lucasalmeida/Documents/GitHub/workshops-es/labs/rpa/sidebar.js",
        "showLastUpdateAuthor": false,
        "showLastUpdateTime": false,
        "breadcrumbs": false
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "path": "labs/docintel",
        "id": "docintel",
        "routeBasePath": "labs/docintel",
        "sidebarPath": "/Users/lucasalmeida/Documents/GitHub/workshops-es/labs/docintel/sidebar.js",
        "showLastUpdateAuthor": false,
        "showLastUpdateTime": false,
        "breadcrumbs": false
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "path": "labs/logistics",
        "id": "logistics",
        "routeBasePath": "labs/logistics",
        "sidebarPath": "/Users/lucasalmeida/Documents/GitHub/workshops-es/labs/logistics/sidebar.js",
        "breadcrumbs": false
      }
    ]
  ],
  "presets": [
    [
      "@docusaurus/preset-classic",
      {
        "docs": false,
        "blog": false,
        "theme": {
          "customCss": "/Users/lucasalmeida/Documents/GitHub/workshops-es/src/css/custom.scss"
        },
        "gtag": {
          "trackingID": "G-P6HQJZPT0C"
        }
      }
    ]
  ],
  "themeConfig": {
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "image": "img/creatorworkflowsnow.github.io.png",
    "navbar": {
      "title": "",
      "logo": {
        "alt": "Workshop Creator Workflows",
        "src": "img/servicenow-logo.png",
        "srcDark": "img/servicenow-logo_dark.png",
        "href": "/",
        "target": "_self"
      },
      "items": [
        {
          "label": "Developer",
          "href": "https://developer.servicenow.com/",
          "position": "left",
          "target": "_blank"
        },
        {
          "label": "Documentation",
          "href": "https://docs.servicenow.com/",
          "position": "left",
          "target": "_blank"
        },
        {
          "label": "Training",
          "href": "https://nowlearning.servicenow.com/",
          "position": "left",
          "target": "_blank"
        },
        {
          "href": "https://github.com/CreatorWorkflowsNow/creatorworkflowsnow.github.io",
          "position": "right",
          "target": "_blank",
          "className": "header-github-link",
          "aria-label": "GitHub repository"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "light",
      "links": [
        {
          "title": "Learn",
          "items": [
            {
              "label": "Blog",
              "href": "https://developer.servicenow.com/blog.do"
            },
            {
              "label": "Dev Community",
              "href": "https://www.servicenow.com/community/developer/ct-p/Developer"
            },
            {
              "label": "Learning Paths",
              "href": "https://developer.servicenow.com/dev.do#!/learn"
            },
            {
              "label": "FREE ServiceNow Instance",
              "href": "https://developer.servicenow.com/"
            },
            {
              "label": "ServiceNow Community",
              "href": "https://www.servicenow.com/community/"
            },
            {
              "label": "Training",
              "href": "https://nowlearning.servicenow.com/"
            }
          ]
        },
        {
          "title": "Reference",
          "items": [
            {
              "label": "API Reference",
              "href": "https://developer.servicenow.com/dev.do#!/reference"
            },
            {
              "label": "Developer Glossary",
              "href": "https://developer.servicenow.com/dev.do#!/guides/vancouver/now-platform/glossary/developer-glossary"
            },
            {
              "label": "Now Create",
              "href": "https://nowlearning.servicenow.com/nowcreate"
            },
            {
              "label": "Product Documentation",
              "href": "https://docs.servicenow.com/"
            }
          ]
        },
        {
          "title": "About ServiceNow",
          "items": [
            {
              "label": "Customer Success Center",
              "href": "https://www.servicenow.com/success.html"
            },
            {
              "label": "Knowledge Conference",
              "href": "https://knowledge.servicenow.com/"
            },
            {
              "label": "LowCodeWorkshops.com",
              "href": "http://lowcodeworkshops.com/"
            },
            {
              "label": "ServiceNow.com",
              "href": "https://www.servicenow.com/"
            },
            {
              "label": "ServiceNow Blogs",
              "href": "https://www.servicenow.com/blogs.html"
            }
          ]
        },
        {
          "title": "Social",
          "items": [
            {
              "label": "Facebook",
              "href": "https://www.facebook.com/servicenow"
            },
            {
              "label": "Instagram",
              "href": "https://www.instagram.com/servicenow/",
              "icon": "instagram"
            },
            {
              "label": "LinkedIn",
              "href": "https://www.linkedin.com/company/servicenow"
            },
            {
              "label": "Twitter",
              "href": "https://twitter.com/servicenow"
            },
            {
              "label": "TikTok",
              "href": "https://www.tiktok.com/@servicenow"
            },
            {
              "label": "YouTube",
              "href": "https://www.youtube.com/user/servicenowinc"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2024 ServiceNow"
    },
    "algolia": {
      "appId": "LE7UCUELDB",
      "apiKey": "198c4f247869bbef524efbc0bfa89c95",
      "indexName": "creatorworkflowsnowio",
      "contextualSearch": true,
      "searchParameters": {},
      "searchPagePath": "search"
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "metadata": [],
    "prism": {
      "additionalLanguages": [],
      "theme": {
        "plain": {
          "color": "#bfc7d5",
          "backgroundColor": "#292d3e"
        },
        "styles": [
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(105, 112, 152)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "string",
              "inserted"
            ],
            "style": {
              "color": "rgb(195, 232, 141)"
            }
          },
          {
            "types": [
              "number"
            ],
            "style": {
              "color": "rgb(247, 140, 108)"
            }
          },
          {
            "types": [
              "builtin",
              "char",
              "constant",
              "function"
            ],
            "style": {
              "color": "rgb(130, 170, 255)"
            }
          },
          {
            "types": [
              "punctuation",
              "selector"
            ],
            "style": {
              "color": "rgb(199, 146, 234)"
            }
          },
          {
            "types": [
              "variable"
            ],
            "style": {
              "color": "rgb(191, 199, 213)"
            }
          },
          {
            "types": [
              "class-name",
              "attr-name"
            ],
            "style": {
              "color": "rgb(255, 203, 107)"
            }
          },
          {
            "types": [
              "tag",
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 114)"
            }
          },
          {
            "types": [
              "operator"
            ],
            "style": {
              "color": "rgb(137, 221, 255)"
            }
          },
          {
            "types": [
              "boolean"
            ],
            "style": {
              "color": "rgb(255, 88, 116)"
            }
          },
          {
            "types": [
              "keyword"
            ],
            "style": {
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "doctype"
            ],
            "style": {
              "color": "rgb(199, 146, 234)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "color": "rgb(178, 204, 214)"
            }
          },
          {
            "types": [
              "url"
            ],
            "style": {
              "color": "rgb(221, 221, 221)"
            }
          }
        ]
      },
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    },
    "mermaid": {
      "theme": {
        "dark": "dark",
        "light": "default"
      },
      "options": {}
    }
  },
  "baseUrlIssueBanner": true,
  "i18n": {
    "defaultLocale": "en",
    "path": "i18n",
    "locales": [
      "en"
    ],
    "localeConfigs": {}
  },
  "onDuplicateRoutes": "warn",
  "customFields": {},
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false
};
